version: '3.7'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server
    ports:
     - "3000:3000"
    volumes:
     - ./server:/server
     - /server/node_modules
    depends_on:
     - redis
  redis:
    container_name: redis
    image: redis:alpine
