version: '3.7'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client
    ports:
      - '80:80'
    depends_on:
      - server

  server:
    build:
      context: ./server/
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
