version: '3.7'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client-dev
    volumes:
      - './client:/client'
      - '/client/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    stdin_open: true
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server-dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:alpine
